---
abstract: 'module for producing/rendering HTML forms'
author:
  - 'Gavin Carr, <gavin@openfusion.com.au>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Formulate
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  HTML::Tabulate: 0.3
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.16
